### ISSUE TITLE
Can not build on Xcode 10.2.1 and unity 2019.2.0b1

### ISSUE THREAD

**Issue by 12343954** [f111fei/react-native-unity-demo#38]
following the "How to Build"

1. Open unity/Cube/Assets/test.unity
OK

2. Click Build => Export Android or Export IOS
OK

3. cd react-native-unity-demo

4. npm install
OK

5. npm run watch
![image](https://user-images.githubusercontent.com/1804003/59599806-10566300-9132-11e9-80e2-18f5e8b6e109.png)

6. open in xcode and build failure
UnityInitStartupTime();    //Use of undeclared identifier 'UnityInitStartupTime'

7. npm run android or npm run ios
OK

how to fix `UnityInitStartupTime() not found` ?
