### ISSUE TITLE
Library doesn't work with Unity version 2018.2.14f1

### ISSUE THREAD

**Issue by ShaubertIlya** [f111fei/react-native-unity-demo#21]
It says that com.unity3d.player does not exist

> Task :react-native-unity-view:compileDebugJavaWithJavac FAILED
Q:\LocalRepo\react-native-unity-demo-master\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityUtils.java:10: error: package com.unity3d.player does not exist
import com.unity3d.player.UnityPlayer;
                         ^
Q:\LocalRepo\react-native-unity-demo-master\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityUtils.java:21: error: cannot find symbol
    private static UnityPlayer unityPlayer;
                   ^
  symbol:   class UnityPlayer
  location: class UnityUtils
Q:\LocalRepo\react-native-unity-demo-master\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityUtils.java:26: error: cannot find symbol
    public static UnityPlayer getPlayer() {
                  ^
  symbol:   class UnityPlayer
  location: class UnityUtils
Q:\LocalRepo\react-native-unity-demo-master\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityView.java:11: error: package com.unity3d.player does not exist
import com.unity3d.player.UnityPlayer;
                         ^
Q:\LocalRepo\react-native-unity-demo-master\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityView.java:19: error: cannot find symbol
    private UnityPlayer view;
            ^
  symbol:   class UnityPlayer
  location: class UnityView
Q:\LocalRepo\react-native-unity-demo-master\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityView.java:21: error: cannot find symbol
    protected UnityView(Context context, UnityPlayer view) {
                                         ^
  symbol:   class UnityPlayer
  location: class UnityView
Q:\LocalRepo\react-native-unity-demo-master\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityViewManager.java:12: error: package com.unity3d.player does not exist
import com.unity3d.player.UnityPlayer;
                         ^
Q:\LocalRepo\react-native-unity-demo-master\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityUtils.java:49: error: cannot find symbol
                unityPlayer = new UnityPlayer(activity);
                                  ^
  symbol: class UnityPlayer
Q:\LocalRepo\react-native-unity-demo-master\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityUtils.java:73: error: cannot find symbol
        UnityPlayer.UnitySendMessage(gameObject, methodName, message);
        ^
  symbol:   variable UnityPlayer
  location: class UnityUtils
Note: Q:\LocalRepo\react-native-unity-demo-master\node_modules\react-native-unity-view\android\src\main\java\com\reactnative\unity\view\UnityViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors

**Comment by papsti7** [comment]
You need to link the `unity-classes.jar`.
Therefore do the following steps:
- Open the project in android studio
- Go to File -> Project Structure -> Modules / react-native-unity-view -> Dependencies -> + -> Add jar dependency
- Navigate to `unity-classes.jar` (usually should be located under `/android/UnityExport/libs/`)
- Resync & Rebuild

**Comment by ShaubertIlya** [comment]
@papsti7 I don't work in Android Studio. I've added this two strings
compile project(':UnityExport')
compile fileTree(dir: '../../../android/UnityExport/libs', include: ['*.jar'])

into my android/app/build.gradle file, but it still doesn't work. I still get this issue about UnityPlayer

**Comment by papsti7** [comment]
@ShaubertIlya I didn't test the solution from the link, but I thought it solves the same issue.

Nevertheless, you need to link the export in `react-native-unity-view` project, which comes with npm, and not in the demo project directly. 

- So navigate to `node_modules/react-native-unity-view/android/`
- Open the `build.gradle`
- Add `implementation files('XXX/UnityExport/libs/unity-classes.jar')`, where XXX is the path to the `UnityExport`folder, to the `dependencies`


In my case, it's the absolute path, like `implementation files('/Users/stefan/Documents/Programming/react-native-unity/react-native-unity-demo/android/UnityExport/libs/unity-classes.jar')`

Let me know if this works.

**Comment by JanOwiesniak** [comment]
This demo works on with Unity 2018.2.14f1 on iOS my iPhone 6s (iOS 12.0.1) and my Nokia 6.1 (Android 8.1.0). [This](https://github.com/f111fei/react-native-unity-demo/issues/21#issuecomment-435162485) helped me to bring it on Android. [That](https://github.com/f111fei/react-native-unity-demo/issues/22#issuecomment-436111690) to make it run on iOS.

**Comment by ShaubertIlya** [comment]
> @ShaubertIlya I didn't test the solution from the link, but I thought it solves the same issue.
> 
> Nevertheless, you need to link the export in `react-native-unity-view` project, which comes with npm, and not in the demo project directly.
> 
> * So navigate to `node_modules/react-native-unity-view/android/`
> * Open the `build.gradle`
> * Add `implementation files('XXX/UnityExport/libs/unity-classes.jar')`, where XXX is the path to the `UnityExport`folder, to the `dependencies`
> 
> In my case, it's the absolute path, like `implementation files('/Users/stefan/Documents/Programming/react-native-unity/react-native-unity-demo/android/UnityExport/libs/unity-classes.jar')`
> 
> Let me know if this works.

I did this and it doesn't work for me

**Comment by papsti7** [comment]
@ShaubertIlya Make sure you clean the project before building again. 
Is it the same error or did something change? 
If it still doesn't wanna work, please install Android Studio and follow the steps from this [comment](https://github.com/f111fei/react-native-unity-demo/issues/21#issuecomment-435162485).

**Comment by f111fei** [comment]
fix https://github.com/f111fei/react-native-unity-demo/commit/56a0e149a17b31c55ea7c0002ebb3ae15807ed71
